// Mock data for demo purposes

export const mockEndpoints = [
  {
    id: '1',
    name: 'Google Maps Platform',
    endpointUrl: 'https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJN1x30md4j4ARbn1eQdUN88U',
    methods: ['GET'],
    apiKey: 'sample-api-key',
    interval: 60,
    alertEmail: 'demo@example.com',
    alertWebhook: null,
    threshold: 2000,
    lastChecked: new Date().toISOString(),
    lastResponse: '200',
    lastStatus: 'up',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Stripe API',
    endpointUrl: 'https://api.stripe.com/v1/charges',
    methods: ['GET', 'POST'],
    apiKey: 'sk_test_sample',
    interval: 60,
    alertEmail: 'demo@example.com',
    alertWebhook: null,
    threshold: 2000,
    lastChecked: new Date().toISOString(),
    lastResponse: '200',
    lastStatus: 'up',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Razorpay API',
    endpointUrl: 'https://api.razorpay.com/v1/transactions',
    methods: ['GET'],
    apiKey: 'rzp_test_sample',
    interval: 60,
    alertEmail: 'demo@example.com',
    alertWebhook: null,
    threshold: 2000,
    lastChecked: new Date().toISOString(),
    lastResponse: '200',
    lastStatus: 'up',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
